name: Atualizar index.json com base nas cifras

on:
  push:
    paths:
      - 'cifras/*.json'
      - '!index.json'

jobs:
  gerar-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependência jq
        run: sudo apt-get install -y jq

      - name: Gerar index.json
        run: |
          echo "[" > index.json
          arquivos=$(find cifras -name '*.json' | sort)
          for file in $arquivos; do
            titulo=$(jq -r .title "$file")
            echo "  {\"title\": \"$titulo\", \"file\": \"${file#cifras/}\"}," >> index.json
          done
          sed -i '$ s/,$//' index.json
          echo "]" >> index.json

      - name: Commit e push do novo index.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.json
          git commit -m "index.json atualizado automaticamente" || echo "Sem alterações"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
